PSUCompBio/FemTech

examples/ex1/ex1.cpp
src/io/input/ReadInputFile.cpp

Please test on Windows at your convenience.

Made minor changes to fix the vector issue

---

examples/ex1/ex1.cpp
include/GlobalVariables.h
include/digitalbrain.h
src/io/PartitionMesh.cpp
src/io/input/ReadInputFile.cpp
src/io/output/WriteVTU.cpp

Made changes in ex1.cpp and other required files.

Changed main() function

---

examples/ex1/ex1.cpp
include/digitalbrain.h
src/io/CMakeLists.txt
src/io/PartitionMesh.cpp
src/io/Partitions.cpp
src/io/SendRecvPartOut.cpp
src/io/input/ReadInputFile.cpp
src/io/output/WriteVTU.cpp

For now, it creates each partition and prints. You can compare elements before and after partitioning. I am also printing all elements for this. To make it easier to read the output on the screen, I am separating element boundaries by numbering them.

Added a new function CreatePartitions() and file Partitions.cpp

---

examples/ex1/ex1.cpp
include/digitalbrain.h
src/io/PartitionMesh.cpp
src/io/Partitions.cpp
src/io/SendRecvPartOut.cpp
src/io/input/ReadInputFile.cpp
src/io/output/FreeArrays.cpp
src/io/output/WriteVTU.cpp

Processor 0 is creating partitions and writing them to VTU files.

Added a function - PrepareVTUData() called before calling WriteVTU

---

include/digitalbrain.h
src/io/input/ReadInputFile.cpp
src/io/output/FreeArrays.cpp

Completed ReadInputFile.
Now, everything is getting read for each processor. No need for the 2nd read now.

Completed ReadInputFile. Added coordinates.

---

examples/ex1/ex1.cpp
include/GlobalVariables.h
src/io/PartitionMesh.cpp
src/io/input/ReadInputFile.cpp

Completed PartitionMesh() function.

---

src/io/input/ReadInputFile.cpp
src/io/output/WriteVTU.cpp

Minor bug in initial distribution corrected.

pvtu file output

---

examples/ex1/CMakeLists.txt
examples/ex1/template.vcxproj.user.in

code will not currently run for me.

trying to fix cmakelists

---

src/io/input/ReadAbaqus.cpp
src/io/input/ReadLsDyna.cpp

 Made fixes in ReadLsDyna (for EOL mark) and ReadAbaqus (for PartID)

---

CMakeLists.txt
examples/CMakeLists.txt

we added combo box in cmake to be able to select between different MPI implementations for windows. I tested on windows (for MS MPI) and Linus using open MPI on ACI. Need to test for mac still.

Updated MPI build options

---

src/io/input/ReadAbaqus.cpp
src/io/input/ReadLsDyna.cpp

Please test with large .k files.

Changed ReadLsDyna (for coordinates array initializing)

---

examples/ex7/ex7.cpp
include/digitalbrain.h
src/fem/GaussQuadrature3D.cpp
src/fem/ShapeFunction_C3D8.cpp
src/fem/ShapeFunctions.cpp

Add 2x2 quad

---

src/fem/ShapeFunctions/ShapeFunction_C3D8.cpp
src/fem/ShapeFunctions/ShapeFunctions.cpp

This corresponds to the feap file program/shp3d.f around line 113 where the xs array is computed, representing the Jacobian transformation array. I am not a big fan of having a multidimensional array for xs. 
I put it in now to keep moving but should be modified in the future. 
I also don't like how the array is being defined each time in this function. this will take time for the computer to find memory. it should be moved to a place where it is not defined each time.

add xs jacobian tranformation array

---

CMakeLists.txt
include/FemTech.h
src/fem/Assembly.cpp
src/fem/CMakeLists.txt
src/fem/Mass/Mass3D.cpp
src/fem/ShapeFunctions/ShapeFunction_C3D8.cpp
src/fem/ShapeFunctions/ShapeFunctions.cpp
src/fem/Stiffness/Stiffness3D.cpp

I moved the mass and stiffness computations into thier own function.  I am still studying the loop in shapefunctions.cpp.  Right now I am not sure how to move local mass and stiffness matrices into the assembly function. Should we make them global? The other thing I am looking at is how we are creating and destroying matrices for each integration point calculation of mass and stiffnees. I worry that this takes time for the computer to find memory. Should these be allocated as global varibles and defined at beginning of simulation ?

moved code to Masss3D and Stiffness3D

---

examples/ex9/ex9.cpp
include/FemTech.h
include/GlobalVariables.h
src/fem/AllocateArrays.cpp
src/fem/CMakeLists.txt
src/io/output/FreeArrays.cpp
src/io/output/WriteVTU.cpp

Here I created two global arrays that should be used: boundary and displacements. They exist for every degree of freedom. These are specified in the "main driver file" (ex9.cpp)  in a new function ApplyBoundaryConditions(). The next step is to modify the existing code to use this format in what has been done and going forward.

Modify how BC/Disp are specified.

---

examples/ex10/ex10.cpp
examples/ex9/ex9.cpp
include/GlobalVariables.h
src/fem/AllocateArrays.cpp

functions are commented out, just starting to add outline.
Stress calculations also need to be added. I will be looking at this soon.

Outline explicit dynamics

---

examples/ex10/ex10.cpp
include/FemTech.h
include/GlobalVariables.h
src/fem/CMakeLists.txt
src/fem/SolidMechanics/CalculateAcclerations.cpp
src/fem/SolidMechanics/GetForce.cpp
src/fem/SolidMechanics/GetForce_3D.cpp
src/timestep/CMakeLists.txt
src/timestep/CalculateTimeStep.cpp
src/timestep/StableTimeStep.cpp
src/timestep/timestep.cpp

I added files that were part of the outline. Most of the functions are empty but the order and process is there. Will continue to add as much as I can.

more updates on explicit outline

---

examples/ex10/ex10.cpp
include/FemTech.h
src/fem/CMakeLists.txt
src/fem/Solver/ExplicitDynamics.cpp

There were some wierd github issues so I think I fixed them here.

Update explicit dynamics 2

---

examples/ex10/ex10.cpp
include/FemTech.h
include/GlobalVariables.h
src/fem/AllocateArrays.cpp
src/fem/CMakeLists.txt
src/fem/SolidMechanics/CalculateAcclerations.cpp
src/fem/SolidMechanics/CalculateFR.cpp
src/fem/SolidMechanics/GetForce_3D.cpp
src/io/output/FreeArrays.cpp

more additions to explicit algorithm including additional files/functions. Many are still empty. Most outline of explicit algorithm is in now, so will move onto filling functions. Will start with GetForce3D.

more updates to explicit algo

---

examples/ex7/ex7.cpp
examples/ex9/ex9.cpp
examples/ex9/ex9.cpp.bk
include/FemTech.h
include/GlobalVariables.h
src/elements/CMakeLists.txt
src/elements/ElementCalculations/CalculateDeformationGradient.cpp
src/fem/Assembly.cpp
src/fem/Mass/Mass3D.cpp
src/fem/ShapeFunctions/GaussQuadrature3D.cpp
src/fem/ShapeFunctions/ShapeFunction_C3D4.cpp
src/fem/ShapeFunctions/ShapeFunction_C3D8.cpp
src/fem/ShapeFunctions/ShapeFunctions.cpp
src/fem/SolidMechanics/GetForce_3D.cpp
src/fem/Solver/SteadyImplicit.cpp
src/fem/Stiffness/Stiffness3D.cpp
src/io/output/FreeArrays.cpp
src/math/math.cpp

Added initial calculation of deformation gradient array, F. I am not 100% convinced it is correct, but will continue to debug. More will be known as getForce function is constructed (since it uses F).

Add deformation gradient calculaton (version 1)

---

include/FemTech.h
src/fem/SolidMechanics/GetForce_3D.cpp
src/materials/CompressibleNeoHookean.cpp
src/math/math.cpp

version 1 - has not been verified and likely has bugs.

added framework for compressilble neohookean

---

include/FemTech.h
src/elements/ElementCalculations/StressDisplacementMatrix.cpp
src/fem/CMakeLists.txt
src/fem/SolidMechanics/GetForce_3D.cpp
src/fem/SolidMechanics/InternalForceUpdate.cpp
src/fem/SolidMechanics/StressUpdate.cpp

infrastructure for internal force update. Need to figure out what to do on stress displacement matrix and force calculation. The commented line of code in InternalForceUpdate in there now corresponds to line 104 of this code:
https://github.com/PSUCompBio/compbio/blob/master/src/eema/src/FEM/SolidMechanics/fe_getForce_3d_normal.cpp

internal force update

---

examples/ex9/CMakeLists.txt
examples/ex9/ex9.cpp
examples/ex9/materials.dat
include/FemTech.h
src/fem/SolidMechanics/StressUpdate.cpp
src/io/CMakeLists.txt
src/io/input/ReadMaterials.cpp
src/materials/CMakeLists.txt
src/materials/StVenantKirchhoff.cpp

I have an analytic solution to compare to. Have additional question about GetForce_3D. I am not seeing where it goes into stress functions (e.g. compressibleneohookean) to calculate cauchy stress (needed for internal force).

add st venant kirchhoff

---

examples/ex9/ex9.cpp
src/fem/SolidMechanics/GetForce_3D.cpp
src/materials/CompressibleNeoHookean.cpp
src/materials/StVenantKirchhoff.cpp

should be correct now. also corrected bug in compressible neohookean. i was computing right cauchy greeen but it should have been left cauchy green. fixed now. Could be moved to blas, but was not sure how to do that. 3x3 matrices need to be convered to column vectors I think.

update st venant-kirchhoff #2

---

examples/ex15/ex15.cpp
src/io/input/ReadInputFile.cpp
src/io/input/ReadLsDyna.cpp

Right now, brain.k file is working without C3D6. Other 3D .k files are also working. But please test 2D files.
Is WriteVTU correct for 2D files as well?

Made changes in .k file reader.

---

CMakeLists.txt
examples/ex7/ex7.cpp
examples/ex9/ex9.cpp
include/GlobalVariables.h
src/elements/CharacteristicLength/CalculateCharacteristicLength_C3D4.cpp
src/elements/CharacteristicLength/CalculateCharacteristicLength_C3D8.cpp
src/elements/ElementCalculations/CalculateDeformationGradient.cpp
src/fem/Assembly.cpp
src/fem/BoundaryConditions.cpp
src/fem/Mass/Mass3D.cpp
src/fem/ShapeFunctions/ShapeFunction_C3D4.cpp
src/fem/ShapeFunctions/ShapeFunction_C3D8.cpp
src/fem/ShapeFunctions/ShapeFunctions.cpp
src/fem/SolidMechanics/CalculateAcclerations.cpp
src/fem/SolidMechanics/CheckEnergy.cpp
src/fem/SolidMechanics/GetForce_3D.cpp
src/fem/SolidMechanics/InternalForceUpdate.cpp
src/fem/SolidMechanics/StressUpdate.cpp
src/fem/SolidMechanics/TrussStressForceUpdate.cpp
src/fem/Solver/SteadyImplicit.cpp
src/fem/Solver/UnsteadyNewmarkImplicit.cpp
src/fem/Stiffness/Stiffness3D.cpp
src/io/PartitionMesh.cpp
src/io/output/FreeArrays.cpp
src/materials/CompressibleNeoHookean.cpp
src/materials/LinearElastic.cpp
src/materials/StVenantKirchhoff.cpp
src/math/DeterminateF.cpp
src/math/InverseF.cpp

Pre-processor directives used to skip debug printing code.

Added debug flag to cmake and code

---

.travis.yml
examples/ex9/ex9.cpp

Travis ci testing
